name: "godot-ci"
on: push

jobs:
  gdtoolkit:
    name: gdformat & gdlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Scony/godot-gdscript-toolkit@master
      - run: gdformat --check Ikaros/core Ikaros/game
        if: always()
      - run: gdlint Ikaros/core Ikaros/game
        if: always()
  godot-check-scripts:
    name: Check scripts
    runs-on: ubuntu-latest
    container:
      image: aronand/godot-alpine:4.3
    defaults:
      run:
        shell: ash {0}
    steps:
      - uses: actions/checkout@v4
      # TODO: Implement the actual check once Jolt works on godot-alpine
      - run: godot --version
