name: "godot-ci"
on: push

jobs:
  gdtoolkit:
    name: "gdtoolkit: gdformat and gdlint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Scony/godot-gdscript-toolkit@master
      - run: gdformat --check Ikaros/core Ikaros/game
        if: always()
      - run: gdlint Ikaros/core Ikaros/game
        if: always()
  godot-check-scripts:
    name: "godot: check scripts"
    runs-on: ubuntu-latest
    container:
      image: aronand/godot-alpine:4.4-dev-7
    defaults:
      run:
        shell: ash {0}
    steps:
      - uses: actions/checkout@v4
      - name: Import project
        working-directory: ./Ikaros
        run: godot --headless --quit --import
      - name: Verify engine version
        run: |
          ENGINE_VERSION=`godot --version | grep -oP "^\d*.\d"`
          PROJECT_ENGINE_VERSION=`grep -oP '^config\/features=PackedStringArray\("\K\d*.\d*' project.godot`
          if [ $ENGINE_VERSION != $PROJECT_ENGINE_VERSION ]; then
            echo "::error::Engine version used in CI ($ENGINE_VERSION) doesn't match project engine version ($PROJECT_ENGINE_VERSION). Make sure you've updated the image if you've recently upgraded the project to a new version of Godot."
            exit 1
          fi
